[window]
opacity = 1.0
option_as_alt = "both"
decorations = "none"
dynamic_padding = true
blur = false

[scrolling]
history = 10000
multiplier = 3

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "Return", mods = "Super", action = "SpawnNewInstance" }
]

[terminal]
shell = { program = "/bin/zsh", args = ["--login"] }
